# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b359ba2aa7671e376ad07bab43f437aad1d37cf181d1f978c74baefff8341ef71ed32243d0809f52220294114478c6f074c4e885b17788af7e918b653a3ea5ca

test:
  secret_key_base: fc21c1060d8d4766bc31214d0a127efb0ee069d96b3eb0cf46ea0c17eceba4d472d9f10e19f8b5fa3cd533e6f219a9ddb6387c78652ee34625e51d8727aa5565

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
